public list.new as 'newList'

public list.newLastItem as 'newLastItem'

public list.getNextItem as 'getNextItem'

public list.getNextItemNesting as 'getNextItemNesting'

public list.nextItemNesting as 'nextItemNesting'

public list.resetIndex as 'resetIndex'

public list.newNextItem as 'newNextItem'

public list.getPriorItem as 'getPriorItem'

public list.getNextItemMatch as 'getNextItemMatch'

public list.getNextItemMatchComp as 'getNextItemMatchComp'