

public processing.processRep as 'processRep'
public processing.processRefValues as 'processRefValues'
public processing.processRefItem as 'processRefItem'

public processing.processLetters as 'processLetters'
public processing.processAppending as 'processAppending'
public processing.processStoreFile as 'processStoreFile'
public processing.processRetrieveFile as 'processRetrieveFile'
public processing.processReplaceLettersList as 'processReplaceLettersList'


public processing.defineAsProcessed as 'defineAsProcessed'
public processing.getBaseRefAtIndex as 'getBaseRefAtIndex'
public processing.getBaseRefUsingFlags as 'getBaseRefUsingFlags'
public processing.getRefLettersList as 'getRefLettersList'
public processing.getRefLettersAlloc as 'getRefLettersAlloc'
public processing.getUnprocessedParams as 'getUnprocessedParams'
public processing.getUnprocessedRegisteredParams as 'getUnprocessedRegisteredParams'